<a href="https://colab.research.google.com/github/raiqahalifialinady10/Raiqah-Alifia-Linady_221230056_Pengantar-Machine-Learning/blob/main/week-02/latihan_praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
'''SOLUSI: Implementasi Preprocessing Pipeline (Versi Angka Berbeda)'''
import numpy as np

# Dataset simulasi: 120 samples, 6 features
np.random.seed(123)
X = np.random.randn(120, 6) * 7 + 10   # Mean=10, Std=7

# SOLUSI 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    normalized = (data - mean) / std
    return normalized

X_normalized = z_score_normalization(X)

# SOLUSI 2: Handle outliers - replace values beyond 2.5 std dengan boundaries
def handle_outliers(data, std_threshold=2.5):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)

    lower_bound = mean - std_threshold * std
    upper_bound = mean + std_threshold * std

    # Clip values ke batas bawah/atas
    cleaned = np.clip(data, lower_bound, upper_bound)
    return cleaned

X_cleaned = handle_outliers(X_normalized)

# SOLUSI 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    n_classes = len(np.unique(labels))
    n_samples = len(labels)

    one_hot = np.zeros((n_samples, n_classes))
    for i, label in enumerate(labels):
        one_hot[i, label] = 1

    return one_hot

labels = np.array([0, 1, 2, 3, 1, 2, 0, 3])
one_hot_labels = one_hot_encoding(labels)

# SOLUSI 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.25):
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)

    # Shuffle indices
    indices = np.random.permutation(n_samples)

    test_indices = indices[:n_test]
    train_indices = indices[n_test:]

    X_train = X[train_indices]
    X_test = X[test_indices]
    y_train = y[train_indices]
    y_test = y[test_indices]

    return X_train, X_test, y_train, y_test

# Generate sample labels (4 kelas)
y = np.random.randint(0, 4, 120)
X_train, X_test, y_train, y_test = train_test_split_numpy(X, y, test_size=0.25)

print("Original data shape:", X.shape)
print("Normalized data mean:", np.mean(X_normalized, axis=0).round(3))
print("Normalized data std:", np.std(X_normalized, axis=0).round(3))
print("One-hot labels shape:", one_hot_labels.shape)
print("One-hot labels:\n", one_hot_labels)
print("Train shape:", X_train.shape, "Test shape:", X_test.shape)

# TEST ASSERTIONS
assert X_normalized.shape == X.shape, "Shape harus tetap sama"
assert np.allclose(X_normalized.mean(axis=0), 0, atol=1e-10), "Mean harus ~0 setelah z-score"
assert np.allclose(X_normalized.std(axis=0), 1, atol=1e-10), "Std harus ~1 setelah z-score"

print("\n✅ Semua assertions berhasil! Solusi benar ")


Original data shape: (120, 6)
Normalized data mean: [ 0.  0.  0. -0. -0.  0.]
Normalized data std: [1. 1. 1. 1. 1. 1.]
One-hot labels shape: (8, 4)
One-hot labels:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
Train shape: (90, 6) Test shape: (30, 6)

✅ Semua assertions berhasil! Solusi benar (versi baru).
